name: Automation Release Reset

on:
  workflow_dispatch:

jobs:
  automation-release-reset:
    runs-on: ubuntu-latest
    concurrency: automation-release
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' #

      - name: Install dependencies
        run: yarn install

      - name: Install jq
        run: sudo apt-get install jq

      - name: Set release version
        run: |
          RELEASE_VERSION=$(curl -fSs https://pokeapi.co/api/v2/pokemon/ditto | jq -r '.height' | cut -d'.' -f1-3)
          echo $RELEASE_VERSION
        shell: bash

      - name: Get latest version
        id: test
        run: |
          set -e
          set -x 
          export GITHUB_JOB_STATUS="success"
          exit 1

          echo ${{ job.status }}
        continue-on-error: true
        shell: bash

      - name: Set environment
        run: |
          if [ "${{ steps.test.outcome }}" == "failure" ]; then
            echo "Previous step failed but we continued."
            echo ${{ job.status }}

            export NEW="asdfasdfasdf"
            echo "NEW=${{ $NEW }}" >> $GITHUB_ENV
          else
            echo "Previous step succeeded."
          fi
        shell: bash

      - name: TEST git
        run: |
          echo $NEW
        shell: bash
        
